
export const enum QUERYENUM {
    UNEXISTINGID = "28745dfgeg235ertert",
    EXISTINGID_01 = "hide%20on%20bush",
    EXISTINGID_02 = "dwg%20viper",
    NORANKINFO_ID = "rlbFqFa8wbKH-P6Mpyj_gYDN5ceypgCbCGbgYOpSA-aZl-k",
    KR = "kr",
    NA1 = "na1",
}


export const EXISTINGID_01_InfoResult = {
    "id": "PAdcKpoBoLc4Zs4nIwXtn1--hhElJGnC3ZpMgZ8k9c0wtg",
    "accountId": "PICVAE-59XRJKW0F9RpFxXlWZeZ9S9JFlQLoicwCrxbL",
    "puuid": "1PebRDVwxeuKe89HIVUIQyJ5jLd1jrDWsSU-kBhJ5fr0c-gdvjswh89k5j4mm24IQyoZJnUU2qnW0g",
    "name": "Hide on bush",
    "profileIconId": 6,
    "revisionDate": 1612774178000,
    "summonerLevel": 414
}

export const EXISTINGID_02_InfoResult = {
    "id": "rlbFqFa8wbKH-P6Mpyj_gYDN5ceypgCbCGbgYOpSA-aZl-k",
    "accountId": "lDlRd6-2I2OAzyZfMeUjDMLVuEnCIaHGjlySGmjuetiQtDw",
    "puuid": "rGVpXNgThotD1OtJpe29nRhIBZHm4dxTgYYawKr_FhkGCN6-d1gsXHQun_49kvpLjAwW7LyqBoaLbg",
    "name": "DWG Viper",
    "profileIconId": 4764,
    "revisionDate": 1606016406000,
    "summonerLevel": 122
}

export const userDetailResult = [
    {
        "freshBlood": false, "hotStreak": false, "inactive": false, "leagueId": "a37af09b-ecb8-3664-9453-cf2b0138dd6e",
        "leaguePoints": 353, "losses": 141, "queueType": "RANKED_SOLO_5x5", "rank": "I", "summonerId": "PAdcKpoBoLc4Zs4nIwXtn1--hhElJGnC3ZpMgZ8k9c0wtg",
        "summonerName": "Hide on bush", "tier": "GRANDMASTER", "veteran": false, "wins": 161
    }
]

export const matchIdEX = {
    withHistory: 5004383873,
    withoutHistory: 112223333,
}

export const matchedGameDetail = {
    "gameId": 5004383873,
    "platformId": "KR",
    "gameCreation": 1613325037193,
    "gameDuration": 1605,
    "queueId": 420,
    "mapId": 11,
    "seasonId": 13,
    "gameVersion": "11.3.357.5376",
    "gameMode": "CLASSIC",
    "gameType": "MATCHED_GAME",
    "teams": [
        {
            "teamId": 100,
            "win": "Fail",
            "firstBlood": false,
            "firstTower": false,
            "firstInhibitor": false,
            "firstBaron": false,
            "firstDragon": true,
            "firstRiftHerald": true,
            "towerKills": 1,
            "inhibitorKills": 0,
            "baronKills": 0,
            "dragonKills": 1,
            "vilemawKills": 0,
            "riftHeraldKills": 1,
            "dominionVictoryScore": 0,
            "bans": [
                {
                    "championId": 77,
                    "pickTurn": 1
                },
                {
                    "championId": 30,
                    "pickTurn": 2
                },
                {
                    "championId": 91,
                    "pickTurn": 3
                },
                {
                    "championId": 526,
                    "pickTurn": 4
                },
                {
                    "championId": 147,
                    "pickTurn": 5
                }
            ]
        },
        {
            "teamId": 200,
            "win": "Win",
            "firstBlood": true,
            "firstTower": true,
            "firstInhibitor": true,
            "firstBaron": true,
            "firstDragon": false,
            "firstRiftHerald": false,
            "towerKills": 9,
            "inhibitorKills": 1,
            "baronKills": 1,
            "dragonKills": 2,
            "vilemawKills": 0,
            "riftHeraldKills": 0,
            "dominionVictoryScore": 0,
            "bans": [
                {
                    "championId": -1,
                    "pickTurn": 6
                },
                {
                    "championId": 164,
                    "pickTurn": 7
                },
                {
                    "championId": 876,
                    "pickTurn": 8
                },
                {
                    "championId": -1,
                    "pickTurn": 9
                },
                {
                    "championId": 30,
                    "pickTurn": 10
                }
            ]
        }
    ],
    "participants": [
        {
            "participantId": 1,
            "teamId": 100,
            "championId": 61,
            "spell1Id": 12,
            "spell2Id": 4,
            "stats": {
                "participantId": 1,
                "win": false,
                "item0": 6655,
                "item1": 2055,
                "item2": 2031,
                "item3": 3040,
                "item4": 4630,
                "item5": 3020,
                "item6": 3340,
                "kills": 4,
                "deaths": 10,
                "assists": 8,
                "largestKillingSpree": 2,
                "largestMultiKill": 2,
                "killingSprees": 1,
                "longestTimeSpentLiving": 269,
                "doubleKills": 1,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 109281,
                "magicDamageDealt": 93672,
                "physicalDamageDealt": 13113,
                "trueDamageDealt": 2495,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 20937,
                "magicDamageDealtToChampions": 18948,
                "physicalDamageDealtToChampions": 1988,
                "trueDamageDealtToChampions": 0,
                "totalHeal": 548,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 11532,
                "damageDealtToObjectives": 1407,
                "damageDealtToTurrets": 216,
                "visionScore": 20,
                "timeCCingOthers": 21,
                "totalDamageTaken": 19489,
                "magicalDamageTaken": 6604,
                "physicalDamageTaken": 12504,
                "trueDamageTaken": 381,
                "goldEarned": 10098,
                "goldSpent": 9965,
                "turretKills": 1,
                "inhibitorKills": 0,
                "totalMinionsKilled": 188,
                "neutralMinionsKilled": 7,
                "neutralMinionsKilledTeamJungle": 1,
                "neutralMinionsKilledEnemyJungle": 4,
                "totalTimeCrowdControlDealt": 269,
                "champLevel": 14,
                "visionWardsBoughtInGame": 5,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 10,
                "wardsKilled": 2,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8230,
                "perk0Var1": 23,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8226,
                "perk1Var1": 250,
                "perk1Var2": 1649,
                "perk1Var3": 0,
                "perk2": 8210,
                "perk2Var1": 4,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8237,
                "perk3Var1": 594,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8345,
                "perk4Var1": 3,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8347,
                "perk5Var1": 0,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8200,
                "perkSubStyle": 8300,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 1,
                "creepsPerMinDeltas": {
                    "10-20": 7.6000000000000005,
                    "0-10": 6.5
                },
                "xpPerMinDeltas": {
                    "10-20": 478.9,
                    "0-10": 384.29999999999995
                },
                "goldPerMinDeltas": {
                    "10-20": 452.7,
                    "0-10": 282.9
                },
                "csDiffPerMinDeltas": {
                    "10-20": 0.6000000000000005,
                    "0-10": -1
                },
                "xpDiffPerMinDeltas": {
                    "10-20": -112.99999999999997,
                    "0-10": -76.69999999999999
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 787.5,
                    "0-10": 480.5
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": -752,
                    "0-10": -152.2
                },
                "role": "SOLO",
                "lane": "MIDDLE"
            }
        },
        {
            "participantId": 2,
            "teamId": 100,
            "championId": 145,
            "spell1Id": 7,
            "spell2Id": 4,
            "stats": {
                "participantId": 2,
                "win": false,
                "item0": 3006,
                "item1": 6672,
                "item2": 6676,
                "item3": 3085,
                "item4": 0,
                "item5": 0,
                "item6": 3363,
                "kills": 6,
                "deaths": 9,
                "assists": 7,
                "largestKillingSpree": 2,
                "largestMultiKill": 2,
                "killingSprees": 3,
                "longestTimeSpentLiving": 567,
                "doubleKills": 1,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 116621,
                "magicDamageDealt": 9179,
                "physicalDamageDealt": 100288,
                "trueDamageDealt": 7153,
                "largestCriticalStrike": 390,
                "totalDamageDealtToChampions": 20895,
                "magicDamageDealtToChampions": 3007,
                "physicalDamageDealtToChampions": 15208,
                "trueDamageDealtToChampions": 2679,
                "totalHeal": 4650,
                "totalUnitsHealed": 3,
                "damageSelfMitigated": 12579,
                "damageDealtToObjectives": 4666,
                "damageDealtToTurrets": 1757,
                "visionScore": 19,
                "timeCCingOthers": 2,
                "totalDamageTaken": 21249,
                "magicalDamageTaken": 7137,
                "physicalDamageTaken": 13507,
                "trueDamageTaken": 604,
                "goldEarned": 10823,
                "goldSpent": 10750,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 182,
                "neutralMinionsKilled": 8,
                "neutralMinionsKilledTeamJungle": 1,
                "neutralMinionsKilledEnemyJungle": 4,
                "totalTimeCrowdControlDealt": 27,
                "champLevel": 13,
                "visionWardsBoughtInGame": 2,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 8,
                "wardsKilled": 4,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 9923,
                "perk0Var1": 65,
                "perk0Var2": 77,
                "perk0Var3": 0,
                "perk1": 8139,
                "perk1Var1": 895,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8138,
                "perk2Var1": 18,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8135,
                "perk3Var1": 2708,
                "perk3Var2": 5,
                "perk3Var3": 0,
                "perk4": 8009,
                "perk4Var1": 1590,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 9103,
                "perk5Var1": 21,
                "perk5Var2": 10,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8100,
                "perkSubStyle": 8000,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 2,
                "creepsPerMinDeltas": {
                    "10-20": 6.8,
                    "0-10": 8.6
                },
                "xpPerMinDeltas": {
                    "10-20": 463.4,
                    "0-10": 334
                },
                "goldPerMinDeltas": {
                    "10-20": 391.6,
                    "0-10": 276
                },
                "csDiffPerMinDeltas": {
                    "10-20": 0.19999999999999973,
                    "0-10": 0.44999999999999973
                },
                "xpDiffPerMinDeltas": {
                    "10-20": -69.55000000000001,
                    "0-10": -30.650000000000006
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 975.6,
                    "0-10": 284.4
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": -26.55000000000001,
                    "0-10": 56.750000000000014
                },
                "role": "DUO_CARRY",
                "lane": "BOTTOM"
            }
        },
        {
            "participantId": 3,
            "teamId": 100,
            "championId": 120,
            "spell1Id": 11,
            "spell2Id": 6,
            "stats": {
                "participantId": 3,
                "win": false,
                "item0": 2055,
                "item1": 3053,
                "item2": 3047,
                "item3": 3078,
                "item4": 1028,
                "item5": 1028,
                "item6": 3364,
                "kills": 8,
                "deaths": 10,
                "assists": 4,
                "largestKillingSpree": 2,
                "largestMultiKill": 2,
                "killingSprees": 2,
                "longestTimeSpentLiving": 309,
                "doubleKills": 3,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 135368,
                "magicDamageDealt": 15084,
                "physicalDamageDealt": 114102,
                "trueDamageDealt": 6181,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 23872,
                "magicDamageDealtToChampions": 3047,
                "physicalDamageDealtToChampions": 19691,
                "trueDamageDealtToChampions": 1133,
                "totalHeal": 17631,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 30680,
                "damageDealtToObjectives": 8568,
                "damageDealtToTurrets": 0,
                "visionScore": 26,
                "timeCCingOthers": 23,
                "totalDamageTaken": 42937,
                "magicalDamageTaken": 15716,
                "physicalDamageTaken": 25831,
                "trueDamageTaken": 1389,
                "goldEarned": 11510,
                "goldSpent": 9583,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 12,
                "neutralMinionsKilled": 119,
                "neutralMinionsKilledTeamJungle": 90,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 206,
                "champLevel": 13,
                "visionWardsBoughtInGame": 10,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 9,
                "wardsKilled": 3,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8010,
                "perk0Var1": 1103,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 9111,
                "perk1Var1": 860,
                "perk1Var2": 240,
                "perk1Var3": 0,
                "perk2": 9105,
                "perk2Var1": 12,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8299,
                "perk3Var1": 1046,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8143,
                "perk4Var1": 630,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8135,
                "perk5Var1": 4122,
                "perk5Var2": 5,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8100,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 3,
                "creepsPerMinDeltas": {
                    "10-20": 0.9,
                    "0-10": 0.1
                },
                "xpPerMinDeltas": {
                    "10-20": 434.4,
                    "0-10": 353.3
                },
                "goldPerMinDeltas": {
                    "10-20": 445.5,
                    "0-10": 303.2
                },
                "csDiffPerMinDeltas": {
                    "10-20": 0.5,
                    "0-10": -0.2
                },
                "xpDiffPerMinDeltas": {
                    "10-20": -231.40000000000003,
                    "0-10": -42.499999999999986
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1806.9,
                    "0-10": 888.3
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": 629,
                    "0-10": -201.2
                },
                "role": "NONE",
                "lane": "JUNGLE"
            }
        },
        {
            "participantId": 4,
            "teamId": 100,
            "championId": 39,
            "spell1Id": 12,
            "spell2Id": 4,
            "stats": {
                "participantId": 4,
                "win": false,
                "item0": 3153,
                "item1": 3057,
                "item2": 3047,
                "item3": 1055,
                "item4": 1055,
                "item5": 3067,
                "item6": 3340,
                "kills": 1,
                "deaths": 5,
                "assists": 3,
                "largestKillingSpree": 0,
                "largestMultiKill": 1,
                "killingSprees": 0,
                "longestTimeSpentLiving": 590,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 101180,
                "magicDamageDealt": 12434,
                "physicalDamageDealt": 84141,
                "trueDamageDealt": 4605,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 10551,
                "magicDamageDealtToChampions": 3533,
                "physicalDamageDealtToChampions": 7017,
                "trueDamageDealtToChampions": 0,
                "totalHeal": 3650,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 12865,
                "damageDealtToObjectives": 705,
                "damageDealtToTurrets": 705,
                "visionScore": 8,
                "timeCCingOthers": 12,
                "totalDamageTaken": 19343,
                "magicalDamageTaken": 7488,
                "physicalDamageTaken": 11183,
                "trueDamageTaken": 671,
                "goldEarned": 8108,
                "goldSpent": 6750,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 180,
                "neutralMinionsKilled": 4,
                "neutralMinionsKilledTeamJungle": 4,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 60,
                "champLevel": 13,
                "visionWardsBoughtInGame": 0,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 5,
                "wardsKilled": 1,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8010,
                "perk0Var1": 171,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8009,
                "perk1Var1": 673,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 9103,
                "perk2Var1": 0,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8299,
                "perk3Var1": 352,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8143,
                "perk4Var1": 321,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8135,
                "perk5Var1": 1363,
                "perk5Var2": 3,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8100,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 4,
                "creepsPerMinDeltas": {
                    "10-20": 8.6,
                    "0-10": 7.4
                },
                "xpPerMinDeltas": {
                    "10-20": 470.2,
                    "0-10": 411.5
                },
                "goldPerMinDeltas": {
                    "10-20": 348.5,
                    "0-10": 275
                },
                "csDiffPerMinDeltas": {
                    "10-20": -1.2000000000000002,
                    "0-10": 0.09999999999999964
                },
                "xpDiffPerMinDeltas": {
                    "10-20": -82.09999999999997,
                    "0-10": -33.39999999999998
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 773.3,
                    "0-10": 462.9
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": -33.19999999999996,
                    "0-10": 194.29999999999998
                },
                "role": "SOLO",
                "lane": "TOP"
            }
        },
        {
            "participantId": 5,
            "teamId": 100,
            "championId": 412,
            "spell1Id": 14,
            "spell2Id": 4,
            "stats": {
                "participantId": 5,
                "win": false,
                "item0": 3190,
                "item1": 3857,
                "item2": 2031,
                "item3": 3114,
                "item4": 3117,
                "item5": 3067,
                "item6": 3364,
                "kills": 1,
                "deaths": 8,
                "assists": 13,
                "largestKillingSpree": 0,
                "largestMultiKill": 1,
                "killingSprees": 0,
                "longestTimeSpentLiving": 349,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 20672,
                "magicDamageDealt": 9268,
                "physicalDamageDealt": 6411,
                "trueDamageDealt": 4992,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 6379,
                "magicDamageDealtToChampions": 4645,
                "physicalDamageDealtToChampions": 876,
                "trueDamageDealtToChampions": 857,
                "totalHeal": 2327,
                "totalUnitsHealed": 5,
                "damageSelfMitigated": 17225,
                "damageDealtToObjectives": 823,
                "damageDealtToTurrets": 305,
                "visionScore": 55,
                "timeCCingOthers": 36,
                "totalDamageTaken": 22400,
                "magicalDamageTaken": 6944,
                "physicalDamageTaken": 14785,
                "trueDamageTaken": 671,
                "goldEarned": 6557,
                "goldSpent": 6185,
                "turretKills": 0,
                "inhibitorKills": 0,
                "totalMinionsKilled": 42,
                "neutralMinionsKilled": 0,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 108,
                "champLevel": 12,
                "visionWardsBoughtInGame": 5,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 28,
                "wardsKilled": 12,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8465,
                "perk0Var1": 2178,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8463,
                "perk1Var1": 871,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8444,
                "perk2Var1": 758,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8242,
                "perk3Var1": 72,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8345,
                "perk4Var1": 3,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8352,
                "perk5Var1": 144,
                "perk5Var2": 1100,
                "perk5Var3": 40,
                "perkPrimaryStyle": 8400,
                "perkSubStyle": 8300,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 5,
                "creepsPerMinDeltas": {
                    "10-20": 2.1,
                    "0-10": 1.8
                },
                "xpPerMinDeltas": {
                    "10-20": 301.8,
                    "0-10": 238.3
                },
                "goldPerMinDeltas": {
                    "10-20": 263.20000000000005,
                    "0-10": 151.8
                },
                "csDiffPerMinDeltas": {
                    "10-20": 0.19999999999999973,
                    "0-10": 0.44999999999999973
                },
                "xpDiffPerMinDeltas": {
                    "10-20": -69.55000000000001,
                    "0-10": -30.650000000000006
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 762.8,
                    "0-10": 257.7
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": -26.55000000000001,
                    "0-10": 56.750000000000014
                },
                "role": "DUO_SUPPORT",
                "lane": "BOTTOM"
            }
        },
        {
            "participantId": 6,
            "teamId": 200,
            "championId": 497,
            "spell1Id": 4,
            "spell2Id": 14,
            "stats": {
                "participantId": 6,
                "win": true,
                "item0": 3860,
                "item1": 3050,
                "item2": 2065,
                "item3": 1028,
                "item4": 0,
                "item5": 3158,
                "item6": 3364,
                "kills": 4,
                "deaths": 2,
                "assists": 20,
                "largestKillingSpree": 2,
                "largestMultiKill": 2,
                "killingSprees": 2,
                "longestTimeSpentLiving": 615,
                "doubleKills": 1,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 34594,
                "magicDamageDealt": 21300,
                "physicalDamageDealt": 7201,
                "trueDamageDealt": 6092,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 7601,
                "magicDamageDealtToChampions": 5064,
                "physicalDamageDealtToChampions": 1656,
                "trueDamageDealtToChampions": 880,
                "totalHeal": 5212,
                "totalUnitsHealed": 4,
                "damageSelfMitigated": 20089,
                "damageDealtToObjectives": 4393,
                "damageDealtToTurrets": 3773,
                "visionScore": 74,
                "timeCCingOthers": 22,
                "totalDamageTaken": 16038,
                "magicalDamageTaken": 3855,
                "physicalDamageTaken": 11279,
                "trueDamageTaken": 903,
                "goldEarned": 9272,
                "goldSpent": 7825,
                "turretKills": 1,
                "inhibitorKills": 0,
                "totalMinionsKilled": 47,
                "neutralMinionsKilled": 0,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 95,
                "champLevel": 14,
                "visionWardsBoughtInGame": 14,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 34,
                "wardsKilled": 10,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": true,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8465,
                "perk0Var1": 2554,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8446,
                "perk1Var1": 1852,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8473,
                "perk2Var1": 446,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8453,
                "perk3Var1": 603,
                "perk3Var2": 1168,
                "perk3Var3": 0,
                "perk4": 8345,
                "perk4Var1": 3,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8347,
                "perk5Var1": 0,
                "perk5Var2": 0,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8400,
                "perkSubStyle": 8300,
                "statPerk0": 5008,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 6,
                "creepsPerMinDeltas": {
                    "10-20": 2.2,
                    "0-10": 1.9
                },
                "xpPerMinDeltas": {
                    "10-20": 461.3,
                    "0-10": 292.4
                },
                "goldPerMinDeltas": {
                    "10-20": 375.79999999999995,
                    "0-10": 215.10000000000002
                },
                "csDiffPerMinDeltas": {
                    "10-20": -0.19999999999999973,
                    "0-10": -0.44999999999999973
                },
                "xpDiffPerMinDeltas": {
                    "10-20": 69.55000000000001,
                    "0-10": 30.650000000000006
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 795.7,
                    "0-10": 172.4
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": 26.55000000000001,
                    "0-10": -56.750000000000014
                },
                "role": "DUO_SUPPORT",
                "lane": "BOTTOM"
            }
        },
        {
            "participantId": 7,
            "teamId": 200,
            "championId": 360,
            "spell1Id": 7,
            "spell2Id": 4,
            "stats": {
                "participantId": 7,
                "win": true,
                "item0": 6673,
                "item1": 6676,
                "item2": 1018,
                "item3": 1038,
                "item4": 1053,
                "item5": 3047,
                "item6": 3363,
                "kills": 12,
                "deaths": 5,
                "assists": 11,
                "largestKillingSpree": 6,
                "largestMultiKill": 2,
                "killingSprees": 2,
                "longestTimeSpentLiving": 608,
                "doubleKills": 2,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 116569,
                "magicDamageDealt": 12817,
                "physicalDamageDealt": 95484,
                "trueDamageDealt": 8267,
                "largestCriticalStrike": 529,
                "totalDamageDealtToChampions": 25131,
                "magicDamageDealtToChampions": 3686,
                "physicalDamageDealtToChampions": 20807,
                "trueDamageDealtToChampions": 637,
                "totalHeal": 5995,
                "totalUnitsHealed": 3,
                "damageSelfMitigated": 14023,
                "damageDealtToObjectives": 5772,
                "damageDealtToTurrets": 1142,
                "visionScore": 35,
                "timeCCingOthers": 6,
                "totalDamageTaken": 23350,
                "magicalDamageTaken": 7842,
                "physicalDamageTaken": 14521,
                "trueDamageTaken": 986,
                "goldEarned": 12556,
                "goldSpent": 11275,
                "turretKills": 1,
                "inhibitorKills": 0,
                "totalMinionsKilled": 161,
                "neutralMinionsKilled": 16,
                "neutralMinionsKilledTeamJungle": 12,
                "neutralMinionsKilledEnemyJungle": 0,
                "totalTimeCrowdControlDealt": 30,
                "champLevel": 14,
                "visionWardsBoughtInGame": 5,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 13,
                "wardsKilled": 5,
                "firstBloodKill": true,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": true,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8010,
                "perk0Var1": 589,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 8009,
                "perk1Var1": 2257,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 9103,
                "perk2Var1": 18,
                "perk2Var2": 30,
                "perk2Var3": 0,
                "perk3": 8299,
                "perk3Var1": 1143,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8139,
                "perk4Var1": 1074,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8135,
                "perk5Var1": 2703,
                "perk5Var2": 4,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8100,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 7,
                "creepsPerMinDeltas": {
                    "10-20": 6.300000000000001,
                    "0-10": 7.6
                },
                "xpPerMinDeltas": {
                    "10-20": 443,
                    "0-10": 341.20000000000005
                },
                "goldPerMinDeltas": {
                    "10-20": 388.6,
                    "0-10": 348.6
                },
                "csDiffPerMinDeltas": {
                    "10-20": -0.19999999999999973,
                    "0-10": -0.44999999999999973
                },
                "xpDiffPerMinDeltas": {
                    "10-20": 69.55000000000001,
                    "0-10": 30.650000000000006
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 995.8,
                    "0-10": 256.2
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": 26.55000000000001,
                    "0-10": -56.750000000000014
                },
                "role": "DUO_CARRY",
                "lane": "BOTTOM"
            }
        },
        {
            "participantId": 8,
            "teamId": 200,
            "championId": 234,
            "spell1Id": 12,
            "spell2Id": 4,
            "stats": {
                "participantId": 8,
                "win": true,
                "item0": 0,
                "item1": 0,
                "item2": 0,
                "item3": 0,
                "item4": 0,
                "item5": 0,
                "item6": 3364,
                "kills": 13,
                "deaths": 7,
                "assists": 13,
                "largestKillingSpree": 4,
                "largestMultiKill": 2,
                "killingSprees": 4,
                "longestTimeSpentLiving": 400,
                "doubleKills": 1,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 106457,
                "magicDamageDealt": 12227,
                "physicalDamageDealt": 93190,
                "trueDamageDealt": 1040,
                "largestCriticalStrike": 214,
                "totalDamageDealtToChampions": 27010,
                "magicDamageDealtToChampions": 4729,
                "physicalDamageDealtToChampions": 22041,
                "trueDamageDealtToChampions": 240,
                "totalHeal": 16131,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 25562,
                "damageDealtToObjectives": 2829,
                "damageDealtToTurrets": 2351,
                "visionScore": 13,
                "timeCCingOthers": 31,
                "totalDamageTaken": 37049,
                "magicalDamageTaken": 11141,
                "physicalDamageTaken": 21984,
                "trueDamageTaken": 3923,
                "goldEarned": 13681,
                "goldSpent": 13175,
                "turretKills": 0,
                "inhibitorKills": 1,
                "totalMinionsKilled": 162,
                "neutralMinionsKilled": 13,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 8,
                "totalTimeCrowdControlDealt": 197,
                "champLevel": 15,
                "visionWardsBoughtInGame": 26,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 7,
                "wardsKilled": 0,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": true,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8010,
                "perk0Var1": 955,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 9111,
                "perk1Var1": 1537,
                "perk1Var2": 520,
                "perk1Var3": 0,
                "perk2": 9105,
                "perk2Var1": 11,
                "perk2Var2": 30,
                "perk2Var3": 0,
                "perk3": 8014,
                "perk3Var1": 780,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8139,
                "perk4Var1": 1172,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8135,
                "perk5Var1": 4441,
                "perk5Var2": 5,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8100,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5003
            },
            "timeline": {
                "participantId": 8,
                "creepsPerMinDeltas": {
                    "10-20": 7,
                    "0-10": 7.5
                },
                "xpPerMinDeltas": {
                    "10-20": 591.9,
                    "0-10": 461
                },
                "goldPerMinDeltas": {
                    "10-20": 574,
                    "0-10": 424.5
                },
                "csDiffPerMinDeltas": {
                    "10-20": -0.6000000000000005,
                    "0-10": 1
                },
                "xpDiffPerMinDeltas": {
                    "10-20": 112.99999999999997,
                    "0-10": 76.69999999999999
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1539.5,
                    "0-10": 632.7
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": 752,
                    "0-10": 152.2
                },
                "role": "SOLO",
                "lane": "MIDDLE"
            }
        },
        {
            "participantId": 9,
            "teamId": 200,
            "championId": 76,
            "spell1Id": 11,
            "spell2Id": 4,
            "stats": {
                "participantId": 9,
                "win": true,
                "item0": 4636,
                "item1": 3135,
                "item2": 3157,
                "item3": 4628,
                "item4": 1082,
                "item5": 3158,
                "item6": 3364,
                "kills": 11,
                "deaths": 3,
                "assists": 16,
                "largestKillingSpree": 9,
                "largestMultiKill": 3,
                "killingSprees": 1,
                "longestTimeSpentLiving": 817,
                "doubleKills": 1,
                "tripleKills": 1,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 202215,
                "magicDamageDealt": 166455,
                "physicalDamageDealt": 18253,
                "trueDamageDealt": 17506,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 30468,
                "magicDamageDealtToChampions": 25835,
                "physicalDamageDealtToChampions": 2673,
                "trueDamageDealtToChampions": 1959,
                "totalHeal": 24484,
                "totalUnitsHealed": 5,
                "damageSelfMitigated": 19532,
                "damageDealtToObjectives": 25687,
                "damageDealtToTurrets": 1956,
                "visionScore": 26,
                "timeCCingOthers": 10,
                "totalDamageTaken": 33796,
                "magicalDamageTaken": 8570,
                "physicalDamageTaken": 24045,
                "trueDamageTaken": 1180,
                "goldEarned": 14008,
                "goldSpent": 13425,
                "turretKills": 2,
                "inhibitorKills": 0,
                "totalMinionsKilled": 33,
                "neutralMinionsKilled": 147,
                "neutralMinionsKilledTeamJungle": 93,
                "neutralMinionsKilledEnemyJungle": 22,
                "totalTimeCrowdControlDealt": 147,
                "champLevel": 16,
                "visionWardsBoughtInGame": 5,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 6,
                "wardsKilled": 3,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": false,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8010,
                "perk0Var1": 581,
                "perk0Var2": 0,
                "perk0Var3": 0,
                "perk1": 9111,
                "perk1Var1": 1909,
                "perk1Var2": 540,
                "perk1Var3": 0,
                "perk2": 9105,
                "perk2Var1": 9,
                "perk2Var2": 50,
                "perk2Var3": 0,
                "perk3": 8014,
                "perk3Var1": 642,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8210,
                "perk4Var1": 15,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8232,
                "perk5Var1": 5,
                "perk5Var2": 10,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8000,
                "perkSubStyle": 8200,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 9,
                "creepsPerMinDeltas": {
                    "10-20": 0.4,
                    "0-10": 0.30000000000000004
                },
                "xpPerMinDeltas": {
                    "10-20": 665.8,
                    "0-10": 395.79999999999995
                },
                "goldPerMinDeltas": {
                    "10-20": 546.3,
                    "0-10": 353.9
                },
                "csDiffPerMinDeltas": {
                    "10-20": -0.5,
                    "0-10": 0.2
                },
                "xpDiffPerMinDeltas": {
                    "10-20": 231.40000000000003,
                    "0-10": 42.499999999999986
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 1177.9,
                    "0-10": 1089.5
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": -629,
                    "0-10": 201.2
                },
                "role": "NONE",
                "lane": "JUNGLE"
            }
        },
        {
            "participantId": 10,
            "teamId": 200,
            "championId": 150,
            "spell1Id": 12,
            "spell2Id": 4,
            "stats": {
                "participantId": 10,
                "win": true,
                "item0": 6630,
                "item1": 1033,
                "item2": 3742,
                "item3": 2055,
                "item4": 1055,
                "item5": 3047,
                "item6": 3340,
                "kills": 2,
                "deaths": 3,
                "assists": 15,
                "largestKillingSpree": 0,
                "largestMultiKill": 1,
                "killingSprees": 0,
                "longestTimeSpentLiving": 1105,
                "doubleKills": 0,
                "tripleKills": 0,
                "quadraKills": 0,
                "pentaKills": 0,
                "unrealKills": 0,
                "totalDamageDealt": 129504,
                "magicDamageDealt": 9741,
                "physicalDamageDealt": 119762,
                "trueDamageDealt": 0,
                "largestCriticalStrike": 0,
                "totalDamageDealtToChampions": 12980,
                "magicDamageDealtToChampions": 2762,
                "physicalDamageDealtToChampions": 10217,
                "trueDamageDealtToChampions": 0,
                "totalHeal": 6961,
                "totalUnitsHealed": 1,
                "damageSelfMitigated": 19755,
                "damageDealtToObjectives": 17996,
                "damageDealtToTurrets": 7843,
                "visionScore": 36,
                "timeCCingOthers": 16,
                "totalDamageTaken": 24628,
                "magicalDamageTaken": 5337,
                "physicalDamageTaken": 16614,
                "trueDamageTaken": 2676,
                "goldEarned": 10777,
                "goldSpent": 8650,
                "turretKills": 3,
                "inhibitorKills": 0,
                "totalMinionsKilled": 196,
                "neutralMinionsKilled": 8,
                "neutralMinionsKilledTeamJungle": 0,
                "neutralMinionsKilledEnemyJungle": 4,
                "totalTimeCrowdControlDealt": 373,
                "champLevel": 15,
                "visionWardsBoughtInGame": 4,
                "sightWardsBoughtInGame": 0,
                "wardsPlaced": 10,
                "wardsKilled": 3,
                "firstBloodKill": false,
                "firstBloodAssist": false,
                "firstTowerKill": true,
                "firstTowerAssist": false,
                "firstInhibitorKill": false,
                "firstInhibitorAssist": false,
                "combatPlayerScore": 0,
                "objectivePlayerScore": 0,
                "totalPlayerScore": 0,
                "totalScoreRank": 0,
                "playerScore0": 0,
                "playerScore1": 0,
                "playerScore2": 0,
                "playerScore3": 0,
                "playerScore4": 0,
                "playerScore5": 0,
                "playerScore6": 0,
                "playerScore7": 0,
                "playerScore8": 0,
                "playerScore9": 0,
                "perk0": 8437,
                "perk0Var1": 709,
                "perk0Var2": 511,
                "perk0Var3": 0,
                "perk1": 8446,
                "perk1Var1": 2682,
                "perk1Var2": 0,
                "perk1Var3": 0,
                "perk2": 8473,
                "perk2Var1": 894,
                "perk2Var2": 0,
                "perk2Var3": 0,
                "perk3": 8451,
                "perk3Var1": 192,
                "perk3Var2": 0,
                "perk3Var3": 0,
                "perk4": 8139,
                "perk4Var1": 640,
                "perk4Var2": 0,
                "perk4Var3": 0,
                "perk5": 8135,
                "perk5Var1": 3737,
                "perk5Var2": 5,
                "perk5Var3": 0,
                "perkPrimaryStyle": 8400,
                "perkSubStyle": 8100,
                "statPerk0": 5005,
                "statPerk1": 5008,
                "statPerk2": 5002
            },
            "timeline": {
                "participantId": 10,
                "creepsPerMinDeltas": {
                    "10-20": 9.8,
                    "0-10": 7.300000000000001
                },
                "xpPerMinDeltas": {
                    "10-20": 552.3,
                    "0-10": 444.9
                },
                "goldPerMinDeltas": {
                    "10-20": 466.9,
                    "0-10": 258.4
                },
                "csDiffPerMinDeltas": {
                    "10-20": 1.2000000000000002,
                    "0-10": -0.09999999999999964
                },
                "xpDiffPerMinDeltas": {
                    "10-20": 82.09999999999997,
                    "0-10": 33.39999999999998
                },
                "damageTakenPerMinDeltas": {
                    "10-20": 806.5,
                    "0-10": 268.6
                },
                "damageTakenDiffPerMinDeltas": {
                    "10-20": 33.19999999999996,
                    "0-10": -194.29999999999998
                },
                "role": "SOLO",
                "lane": "TOP"
            }
        }
    ],
    "participantIdentities": [
        {
            "participantId": 1,
            "player": {
                "platformId": "KR",
                "accountId": "DG4HSN9r6dRr-3ffSiiCq6NgA5PGu_dAqJJEqtBC0BXoxlQ8kvtXnu3r",
                "summonerName": "KT VicLa",
                "summonerId": "asGKOTLnhZ0C0TsmxBFpzOl71gcM2CpRC-aPk7pwhOYZRZQ",
                "currentPlatformId": "KR",
                "currentAccountId": "DG4HSN9r6dRr-3ffSiiCq6NgA5PGu_dAqJJEqtBC0BXoxlQ8kvtXnu3r",
                "matchHistoryUri": "/v1/stats/player_history/KR/2439360128307136",
                "profileIcon": 4069
            }
        },
        {
            "participantId": 2,
            "player": {
                "platformId": "KR",
                "accountId": "Aeb685SY2bkbxehGzPKZREuZqYlXZcxFxeNF7bO7I_LjlK3YTcuvihce",
                "summonerName": "난 모험가",
                "summonerId": "NpY-xEMSikSVznbSYO2Ld-a5m7v-TJC4uJBo7EiZ5VatKG4",
                "currentPlatformId": "KR",
                "currentAccountId": "Aeb685SY2bkbxehGzPKZREuZqYlXZcxFxeNF7bO7I_LjlK3YTcuvihce",
                "matchHistoryUri": "/v1/stats/player_history/KR/1999989230866272",
                "profileIcon": 2076
            }
        },
        {
            "participantId": 3,
            "player": {
                "platformId": "KR",
                "accountId": "Q4abnkGhqGUFhSoHQhR7Nd6ee5fJko-z8hO-Pc3t49-3Uhk4yLHRTPuU",
                "summonerName": "Juhana",
                "summonerId": "PQVVWl5X9pL8_rSTnxbp6AT52WVNSTFadsWtpqOkQ7A_1Oo",
                "currentPlatformId": "KR",
                "currentAccountId": "Q4abnkGhqGUFhSoHQhR7Nd6ee5fJko-z8hO-Pc3t49-3Uhk4yLHRTPuU",
                "matchHistoryUri": "/v1/stats/player_history/KR/2287641709235904",
                "profileIcon": 4755
            }
        },
        {
            "participantId": 4,
            "player": {
                "platformId": "KR",
                "accountId": "SOVFkJLPfFGoBsU3SHCFTqyBzCCB_YdFGPnkC45jrk4PxBDKBO6fUs9N",
                "summonerName": "우린 함께야1",
                "summonerId": "DiBdSQAY1zOJPvyhkZ1HVvyPbcA9KVUpKWFkmMdmR2rGq9U",
                "currentPlatformId": "KR",
                "currentAccountId": "SOVFkJLPfFGoBsU3SHCFTqyBzCCB_YdFGPnkC45jrk4PxBDKBO6fUs9N",
                "matchHistoryUri": "/v1/stats/player_history/KR/2183772254940320",
                "profileIcon": 938
            }
        },
        {
            "participantId": 5,
            "player": {
                "platformId": "KR",
                "accountId": "ODVkXAakPqxRxqcA4QiKASTanuoGAweNmlbpV0aiMkS03FM",
                "summonerName": "뀨와룡존버",
                "summonerId": "Mnks1i6ow0NDHN0lIiVmFjcVX8g-iyubGKFxKxUC4nyn984",
                "currentPlatformId": "KR",
                "currentAccountId": "ODVkXAakPqxRxqcA4QiKASTanuoGAweNmlbpV0aiMkS03FM",
                "matchHistoryUri": "/v1/stats/player_history/KR/207083100",
                "profileIcon": 4568
            }
        },
        {
            "participantId": 6,
            "player": {
                "platformId": "KR",
                "accountId": "SDJxDNURaM3vF44JxreBBasulBycv3jcjRs9wP1a65iNe_1pTv7hEWCp",
                "summonerName": "Palette6",
                "summonerId": "t4GLLt17p1TppnJlonVEveB6wwo9qhYyMMLaXTPZ3hTJ7O_SSVszABm5-Q",
                "currentPlatformId": "KR",
                "currentAccountId": "SDJxDNURaM3vF44JxreBBasulBycv3jcjRs9wP1a65iNe_1pTv7hEWCp",
                "matchHistoryUri": "/v1/stats/player_history/KR/2645854464132448",
                "profileIcon": 4872
            }
        },
        {
            "participantId": 7,
            "player": {
                "platformId": "KR",
                "accountId": "n0p5ewBzWMJsXJwgvD44MBMWpDcCXPFUoNjWn71qajfERpQ",
                "summonerName": "Himnae ",
                "summonerId": "-VJ_YixjyMPG9M2rhr40ug9jEFLt2PjyMZMWwqXPGPaEh2E",
                "currentPlatformId": "KR",
                "currentAccountId": "n0p5ewBzWMJsXJwgvD44MBMWpDcCXPFUoNjWn71qajfERpQ",
                "matchHistoryUri": "/v1/stats/player_history/KR/210097346",
                "profileIcon": 4882
            }
        },
        {
            "participantId": 8,
            "player": {
                "platformId": "KR",
                "accountId": "PICVAE-59XRJKW0F9RpFxXlWZeZ9S9JFlQLoicwCrxbL",
                "summonerName": "Hide on bush",
                "summonerId": "PAdcKpoBoLc4Zs4nIwXtn1--hhElJGnC3ZpMgZ8k9c0wtg",
                "currentPlatformId": "KR",
                "currentAccountId": "PICVAE-59XRJKW0F9RpFxXlWZeZ9S9JFlQLoicwCrxbL",
                "matchHistoryUri": "/v1/stats/player_history/KR/3440481",
                "profileIcon": 6
            }
        },
        {
            "participantId": 9,
            "player": {
                "platformId": "KR",
                "accountId": "oDCmwmFvUDN6cuKt1OPuqUL4AG7brdaBBp4Nkmt-QWrcgiM",
                "summonerName": "엘 림",
                "summonerId": "2WnAPU_hnqHIwohrQWx7u-lS3b-gDElLl65MxBSlKy0CTow",
                "currentPlatformId": "KR",
                "currentAccountId": "oDCmwmFvUDN6cuKt1OPuqUL4AG7brdaBBp4Nkmt-QWrcgiM",
                "matchHistoryUri": "/v1/stats/player_history/KR/206501884",
                "profileIcon": 4025
            }
        },
        {
            "participantId": 10,
            "player": {
                "platformId": "KR",
                "accountId": "pw6DGA9CHvp6HeWfFjVR1MOMENbdcuKqZNasu9-3i3edbSc",
                "summonerName": "Vikutorika",
                "summonerId": "tQvT3hTKaSf39JASDPsvRl4ESEFrw7rzIbNHDI7C30VApEs",
                "currentPlatformId": "KR",
                "currentAccountId": "pw6DGA9CHvp6HeWfFjVR1MOMENbdcuKqZNasu9-3i3edbSc",
                "matchHistoryUri": "/v1/stats/player_history/KR/205499309",
                "profileIcon": 4535
            }
        }
    ]
}