name: Build docker image and publish on docker hub

on: workflow_dispatch
jobs:
  docker-build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code from git
        uses: actions/checkout@v2

      - name: Set up Docker BuildX
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      - name: Setting environment variables
        run: |
          chmod +x ./scripts/set-env.sh
          ./scripts/set-env.sh
        env:
          PORT: ${{secrets.PORT}}
          RIOT_TOKEN: ${{secrets.RIOT_TOKEN}}
          MONGODB_URL: ${{secrets.MONGODB_URL}}
          JWT_SECRET: ${{secrets.JWT_SECRET}}
          COOKIE_DOMAIN_PROD: ${{secrets.COOKIE_DOMAIN_PROD}}
      - name: Building docker image
        run: make build

      - name: Publishing docker image to docker hub
        run: make push